version: '3.9'

services:

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend

      #- ./frontend:/frontend
      #- ./data/web:/vol/web
